#!/usr/bin/env python3
"""
Turn a capture session into a pentest brief plus a replay harness.

`mpfeed.py` produces the raw view (index/surface/flags/flows). This condenses
that into ONE file to act on — a ranked endpoint list with concrete test
candidates — and generates a self-contained `replay.py` for the session so
captured requests can be re-sent with modifications.

Writes into the session directory:
  BRIEF.md    ranked attack surface + test candidates   <- read this
  replay.py   replay harness (DRY RUN unless --send)

Usage: brief.py <session-dir>
"""
from __future__ import annotations

import json
import pathlib
import sys
from collections import Counter, defaultdict

WRITE_METHODS = {"POST", "PUT", "PATCH", "DELETE"}

REPLAY_TEMPLATE = '''#!/usr/bin/env python3
"""
Replay harness for {session_name}.

DRY RUN by default: prints the request it would send and exits. Pass --send to
actually transmit. Generated by brief.py; safe to edit.

  ./replay.py --list                       show captured requests
  ./replay.py 3                            dry-run request #3
  ./replay.py 3 --send                     send it unmodified
  ./replay.py 3 --set '{{"MTI":"4009"}}'     merge JSON into the body, then send
  ./replay.py 3 --set-body-json '{{"a":1}}'  set requestBody (base64) and re-sign
  ./replay.py 3 --raw-body '<text>'        replace the whole body verbatim

Only use against systems you are authorised to test.
"""
import argparse, json, pathlib, sys, urllib.request, urllib.error

HERE = pathlib.Path(__file__).resolve().parent
FLOWS = HERE / "flows.jsonl"

# Optional signer: some APIs carry a custom integrity field (e.g. macIn) that
# must be recomputed whenever the body changes. If scripts/zc-macin.py (or an
# equivalent, target-specific signer) exists, it's loaded here; otherwise no-op.
SIGNER = None
try:
    sys.path.insert(0, str(HERE.parent.parent / "scripts"))
    from zc_macin import compute_macin as _zc  # noqa
    SIGNER = _zc
except Exception:
    try:
        import importlib.util
        _p = HERE.parent.parent / "scripts" / "zc-macin.py"
        if _p.exists():
            _s = importlib.util.spec_from_file_location("zc_macin", _p)
            _m = importlib.util.module_from_spec(_s); _s.loader.exec_module(_m)
            SIGNER = _m.compute_macin
    except Exception:
        SIGNER = None


def load():
    return [json.loads(l) for l in FLOWS.open()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("index", nargs="?", type=int)
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--send", action="store_true", help="actually transmit (default is dry run)")
    ap.add_argument("--set", help="JSON object merged into the request body")
    ap.add_argument("--set-body-json", help="JSON string -> base64 into requestBody, then re-sign")
    ap.add_argument("--raw-body", help="replace the request body verbatim")
    a = ap.parse_args()

    rows = load()
    if a.list or a.index is None:
        for r in rows:
            print(f"{{r['i']:4}}  {{r['method']:6}} {{r['host']}}{{r['path']}}  -> {{r['status']}}")
        return 0

    r = next((x for x in rows if x["i"] == a.index), None)
    if not r:
        sys.exit(f"no request #{{a.index}}")

    url = f"{{r['scheme']}}://{{r['host']}}{{r['path']}}"
    body = r.get("req_body") or ""

    if a.raw_body is not None:
        body = a.raw_body
    elif a.set or a.set_body_json:
        try:
            doc = json.loads(body) if body else {{}}
        except Exception:
            sys.exit("body is not JSON; use --raw-body")
        if a.set:
            doc.update(json.loads(a.set))
        if a.set_body_json:
            import base64
            doc["requestBody"] = base64.b64encode(a.set_body_json.encode()).decode()
        if SIGNER and "macIn" in doc:
            doc["macIn"] = SIGNER(doc)
            print("[*] macIn re-signed", file=sys.stderr)
        body = json.dumps(doc, separators=(",", ":"))

    headers = {{k: v for k, v in (r.get("req_headers") or {{}}).items()
               if k.lower() not in ("content-length", "host", "accept-encoding")}}

    print(f"{{r['method']}} {{url}}")
    for k, v in headers.items():
        print(f"{{k}}: {{v}}")
    print()
    print(body[:2000])
    sys.stdout.flush()

    if not a.send:
        print("\\n[dry run] pass --send to transmit", file=sys.stderr)
        return 0

    req = urllib.request.Request(url, data=body.encode() if body else None,
                                 headers=headers, method=r["method"])
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            print(f"\\n<- {{resp.status}}")
            print(resp.read(4000).decode("utf-8", "replace"))
    except urllib.error.HTTPError as e:
        print(f"\\n<- {{e.code}}")
        print(e.read(4000).decode("utf-8", "replace"))
    except Exception as e:
        print(f"\\n<- transport error: {{e}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def risk_of(ep: dict) -> tuple[int, list[str]]:
    """Rank an endpoint and say why."""
    score, why = 0, []
    if ep["unauth_2xx"]:
        score += 40
        why.append("answers 2xx with no Authorization/Cookie")
    if ep["idor"]:
        score += 25
        why.append(f"object refs in path/query ({len(ep['idor'])} seen)")
    if ep["methods"] & WRITE_METHODS:
        score += 15
        why.append("state-changing method")
    if ep["flags"]:
        score += 10
        why.append("secrets/PII in traffic: " + ",".join(sorted(ep["flags"])[:4]))
    if ep["body_params"]:
        score += 10
        why.append(f"{len(ep['body_params'])} body fields (mass-assignment / injection surface)")
    if any(s and s >= 500 for s in ep["statuses"]):
        score += 5
        why.append("5xx observed")
    return score, why


def main() -> int:
    if len(sys.argv) < 2:
        sys.exit("usage: brief.py <session-dir>")
    sess = pathlib.Path(sys.argv[1])
    flows_f = sess / "flows.jsonl"
    if not flows_f.exists():
        sys.exit(f"no flows.jsonl in {sess}")

    rows = [json.loads(l) for l in flows_f.open()]
    if not rows:
        sys.exit("no flows captured")

    eps: dict[tuple, dict] = {}
    hosts: Counter = Counter()
    all_flags: Counter = Counter()
    auth_schemes: Counter = Counter()

    for r in rows:
        hosts[r["host"]] += 1
        for f in r.get("flag_types", []):
            all_flags[f] += 1
        auth_schemes[r.get("auth_scheme") or "none"] += 1

        tmpl = r["path"]
        for seg in r["path"].split("/"):
            if seg.isdigit() or (len(seg) in (24, 36) and all(c in "0123456789abcdef-" for c in seg.lower())):
                tmpl = tmpl.replace(seg, "{id}")
        key = (r["host"], tmpl)
        e = eps.setdefault(key, {
            "host": r["host"], "tmpl": tmpl, "hits": 0, "methods": set(),
            "statuses": set(), "auth": 0, "unauth": 0, "unauth_2xx": False,
            "idor": set(), "flags": set(), "body_params": set(), "examples": [],
        })
        e["hits"] += 1
        e["methods"].add(r["method"])
        e["statuses"].add(r["status"])
        e["auth" if r.get("authenticated") else "unauth"] += 1
        if not r.get("authenticated") and r["status"] and 200 <= r["status"] < 300:
            e["unauth_2xx"] = True
        e["idor"].update(r.get("idor_candidates") or [])
        e["flags"].update(r.get("flag_types") or [])
        try:
            doc = json.loads(r.get("req_body") or "")
            if isinstance(doc, dict):
                e["body_params"].update(list(doc.keys())[:40])
        except Exception:
            pass
        if len(e["examples"]) < 3:
            e["examples"].append(r["i"])

    ranked = []
    for e in eps.values():
        score, why = risk_of(e)
        ranked.append((score, why, e))
    ranked.sort(key=lambda t: (-t[0], t[2]["tmpl"]))

    out = [
        f"# Pentest brief — {sess.name}",
        "",
        f"{len(rows)} requests · {len(eps)} endpoints · {len(hosts)} hosts",
        "",
        "## Hosts",
        "",
    ]
    for h, c in hosts.most_common():
        out.append(f"- `{h}` — {c}")
    out += ["", "## Auth model", ""]
    for k, v in auth_schemes.most_common():
        out.append(f"- {k}: {v} requests")
    if all_flags:
        out += ["", "## Flagged in traffic", ""]
        for k, v in all_flags.most_common():
            out.append(f"- {k}: {v}")

    out += ["", "## Endpoints, highest risk first", "",
            "| risk | method | endpoint | hits | statuses | unauth | why |",
            "|---|---|---|---|---|---|---|"]
    for score, why, e in ranked:
        st = ",".join(str(s) for s in sorted(x for x in e["statuses"] if x))
        out.append(
            f"| {score} | {'/'.join(sorted(e['methods']))} | `{e['host']}{e['tmpl']}` | "
            f"{e['hits']} | {st} | {e['unauth']} | {'; '.join(why) or '-'} |")

    out += ["", "## Test candidates", ""]
    bac = [e for s, w, e in ranked if e["unauth_2xx"]]
    if bac:
        out += ["### Broken access control — 2xx without credentials", ""]
        for e in bac:
            out.append(f"- `{'/'.join(sorted(e['methods']))} {e['host']}{e['tmpl']}` "
                       f"({e['unauth']} unauthenticated hits) — is it genuinely public?")
        out.append("")
    idor = [e for s, w, e in ranked if e["idor"]]
    if idor:
        out += ["### Object references — IDOR / BOLA", ""]
        for e in idor:
            out.append(f"- `{e['host']}{e['tmpl']}` — {', '.join(sorted(e['idor'])[:6])}")
        out.append("")
    fat = [e for s, w, e in ranked if len(e["body_params"]) >= 3]
    if fat:
        out += ["### Body fields — mass assignment / injection", ""]
        for e in fat:
            out.append(f"- `{e['host']}{e['tmpl']}` — {', '.join(sorted(e['body_params'])[:14])}")
        out.append("")

    out += ["## Replay", "",
            "Dry run by default; `--send` transmits.", "",
            "```bash",
            f"cd {sess}",
            "./replay.py --list",
            "./replay.py 1                 # dry run",
            "./replay.py 1 --send          # send unmodified",
            "./replay.py 1 --set '{\"MTI\":\"4009\"}' --send",
            "```", ""]

    if not any(e["auth"] for e in eps.values()):
        out += ["> **Coverage note:** every captured request was unauthenticated. "
                "The authenticated surface — where IDOR/BOLA and business-logic "
                "flaws usually live — is not represented here.", ""]

    (sess / "BRIEF.md").write_text("\n".join(out))

    rp = sess / "replay.py"
    rp.write_text(REPLAY_TEMPLATE.format(session_name=sess.name))
    rp.chmod(0o755)

    print(f"[+] {sess/'BRIEF.md'}")
    print(f"[+] {rp}")
    print(f"    {len(rows)} requests, {len(eps)} endpoints, top risk {ranked[0][0] if ranked else 0}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
